apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-debug
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: debug
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        envFrom:
        - configMapRef:
            name: debug-env-config
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - container-debug
              topologyKey: kubernetes.io/hostname