apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-debug
  labels:
    app: container-debug
    app.kubernetes.io/name: container-debug
    app.kubernetes.io/component: debugging-tool
    app.kubernetes.io/part-of: container-debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-debug
  template:
    metadata:
      labels:
        app: container-debug
        app.kubernetes.io/name: container-debug
        app.kubernetes.io/component: debugging-tool
        app.kubernetes.io/part-of: container-debug
    spec:
      containers:
      - name: debug
        image: ghcr.io/cotocisternas/container-debug:latest
        imagePullPolicy: Always
        command: ["/bin/bash"]
        args: 
        - "-c"
        - |
          echo "=== Container Debug Started ===" >&2
          echo "" >&2
          if [ -f /debug-docs/debug-instructions.md ]; then
            cat /debug-docs/debug-instructions.md >&2
          else
            echo "Debug instructions not available. Run 'debug-demo' for help." >&2
          fi
          echo "" >&2
          echo "=== Ready for debugging ===" >&2
          echo "" >&2
          while true; do sleep 3600; done
        stdin: true
        tty: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
            add:
            - NET_RAW  # Required for ping
        env:
        - name: TZ
          value: "UTC"
        volumeMounts:
        - name: debug-instructions
          mountPath: /debug-docs
          readOnly: true
      volumes:
      - name: debug-instructions
        configMap:
          name: debug-scripts
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault