apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-debug
spec:
  template:
    spec:
      containers:
      - name: debug
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: debug-env-config